name: CI/CD DevOps Final

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Clonar el repositorio
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2. Configurar Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      # 3. Instalar dependencias (incluyendo devDependencies)
      - name: Install dependencies
        run: npm install --include=dev

      # 4. Ejecutar tests
      - name: Run tests
        run: npm test

      # 5. Iniciar sesión en Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # 6. Construir la imagen Docker
      - name: Build Docker image
        run: docker build -t barreradk/holamundo-devops:latest .

      # 7. Subir la imagen a Docker Hub
      - name: Push Docker image
        run: docker push barreradk/holamundo-devops:latest

      # 8. Desplegar en Render (solo si ya quieres desplegar)
      - name: Deploy to Render
        if: success() # se ejecuta solo si los tests pasaron
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
        run: |
          curl -X POST https://api.render.com/deploy/srv-XXXXXXXXXXXX \
          -H "Authorization: Bearer $RENDER_API_KEY"
